defaults:
  - _self_
  - nnet: SPDNet
  - dataset: HDM05_SPD
  - override hydra/launcher: joblib
fit:
  epochs: 200
  batch_size: 30
  threadnum: 10
  is_writer: True
  cycle: 1
  seed: 1024
  is_save: False
  device: cpu

hydra:
  run:
    dir: ./outputs/${dataset.dataset}
  sweep:
    dir: ./outputs/${dataset.dataset}
    subdir: '.'
  launcher:
    n_jobs: -1
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        filename: default.log
